.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  QT_DEBUG_PLUGINS: 1
  QT_QPA_PLATFORM: offscreen

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - apt update
  - apt install -y xvfb # Sets up a headless display
  - xvfb :99 & export DISPLAY=:99
  - sleep 3

stages:
  - Test

test:
  stage: Test
  script:
    - pip install -e .
    - pip install -r requirements_dev.txt
    - xvfb-run py.test -s --cov=quantify --cov-report xml --cov-report html --cov-report term --cov-config=.coveragerc --color=yes
  artifacts:
    paths:
      - htmlcov
      - coverage.xml
    reports:
      cobertura: coverage.xml
    when: always

test-win:
  before_script:
    - choco install python --version=3.8.3 -y
  extends:
    - .shared_windows_runners
    - test
  script:
    - python3 -m pip install -e .
    - python3 -m pip install -r requirements_dev.txt
    - py.test -s --cov=quantify --cov-report xml --cov-report html --cov-report term --cov-config=.coveragerc --color=yes
