workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "api"'

# If you want to define variables, be sure to carefully override ones in quantify-os/ci/common.yml
# variables:
#   FOO: bar

include:
  - project: "quantify-os/ci"
    ref: main
    file: "/python-vanilla.yml"
  - project: "quantify-os/ci"
    ref: main
    file: "/python-windows.yml"
